name: Docker Compose

on:
    push:
        branches:
            - "**"
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    docker:
        name: Docker Compose Test
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:latest
                options: --privileged
                ports:
                    - 2375:2375

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker Compose
              run: docker-compose build

            - name: Start BMS Network
              run: docker network create bms-network

            - name: Start Docker Compose
              run: docker-compose up -d

            - name: Wait for services to be ready
              run: |
                  docker-compose exec -T bff-service bash -c 'while !</dev/tcp/localhost/8080; do sleep 1; done'

            - name: Test BFF service
              run: curl -s http://localhost:8080

            - name: Stop Docker Compose
              run: docker-compose down
